### ISSUE TITLE
Eprom seems like its not working

### ISSUE THREAD

**Issue by killpop** [piodabro/WPro58#1]
Hi, I flashed your .bin file today and it seems like I have to calibrate the rssi every time I power up the module otherwise it will not select a channel. Other than that, everything seems to work great. Is this a problem with the eprom or something else?

**Comment by piodabro** [comment]
On mine module it works ok. Maybe EEPROM is dead?

**Comment by piodabro** [comment]
v0.2 has some fix of EEPROM version byte (i've increased the version byte, so bytes saved to eeprom are ignored and default ones used, then written to eeprom).
