### ISSUE TITLE
how to compile it?

### ISSUE THREAD

**Issue by Jeffrihr** [piodabro/WPro58#14]
hi there, I'm new in this hobby
can you tell me how to compile that files?
I want to customize my own screensaver logo, I have to conver my BMP to hex code
now I just wannt to compile that code files fo BIN file
thank you

**Comment by piodabro** [comment]
There will not be screensaver logo anymore. Current code has modifiable callsign displayed on screensaver.
To compile current code You have to download SW4STM32. Link is in README file.
SW4STM32 is a Eclipse based IDE. This repo contains project for this IDE.

**Comment by Jeffrihr** [comment]
thank you for your answer, I'll try it
