### ISSUE TITLE
OLED flip screen feature

### ISSUE THREAD

**Issue by mgrapiniak** [piodabro/WPro58#15]
Please implement flip screen feature.
Automatically or manually set.

**Comment by mihero** [comment]
pro58 doesn't have any orientation sensors so only possibility is manual.
picked from forum that request is to have 180degree orientation change but feature could include also 90 and 270 degree orientation change

**Comment by piodabro** [comment]
Yep, but rotating vertically needs to reimplement views to vertical 128 x 64 screen.
I think we should start with simple upside-down rotating, and then edit status clasess to support vertical views finally adding 90/270 deg options.

**Comment by mihero** [comment]
True. simple upside down should be easy task.
supporting 90degree would most likely need redesign on graph screens.

**Comment by mgrapiniak** [comment]
Hey guys,
Any chance to implement this feature in upcoming release? How would you estimate work needed for making this happen? Perhaps I could submit PR but to be honest I would require some help :)

**Comment by piodabro** [comment]
This have to wait until i make scrolling settings menu (cause it can handle only 8 entries on single screen)
