### ISSUE TITLE
option to make fatshark button pins replicate jog wheel

### ISSUE THREAD

**Issue by stevefoxuk** [piodabro/WPro58#22]
an option to make the fatshark button pins activate and navigate the menu system would be usefull.

1 pin for select and the two other pins for up and down/ left right in the menu system.
allowing external buttons to replace the fragile and fiddly jog wheel.

**Comment by piodabro** [comment]
To add this feature in settings menu i have to work on settings menu scrolling (cause screen can handle only 8 entires). 
This can be done fast as a separate .bin file with changed buttons pins to FS pins (compiled with no possibility to change in menu).

**Comment by stevefoxuk** [comment]
So are you saying it can be done in a seperate release without menu change.
Or...
It can be done with the new menu but your not going too.
Or.....
It can be done with the new menu and you will but it will take time?

I'm a little confused ha ha

Steve.

**Comment by stevefoxuk** [comment]
OK, I've read it again when I'm not tired and I understand, basically you can add no more items in the firmware untill you have done menu scrolling as it only allows 8 lines and you are already using all 8 lines.

The separate bin file would have the buttons changed but permanently as it would be written into the firmware directly instead of a switchable option due to current limitations because of the menu structure.

It can be done on a switchable menu but will take time as you have to do them menu scroll before any new features, buttons or anything else can be implemented..

Do I have this right now? Ha ha 


Steve.

**Comment by piodabro** [comment]
Menu scrolling is almost done ;)
