### ISSUE TITLE
Feature request : how to edit - LOGO"/Callsign in screensaver mode !

### ISSUE THREAD

**Issue by yo8aiv** [piodabro/WPro58#4]
Yep that's exactly what i meant on rcgroups.
Feature: **how to edit - LOGO"/Callsign in screensaver mode** !

Very nice job.
Cheers.

**Comment by piodabro** [comment]
It will be possible when I release open-source code. Then you have to compile your own version with changed logo in header file.

**Comment by piodabro** [comment]
In the tools dir is a tool to create byte array from graphics (B&W BMP file, 128x64pix).
Just make your own logo and use the tool to convert it to code.
In this tool set byte order to horizontal.

Then change the logo.h header file and now you have your own logo ;)

**Comment by yo8aiv** [comment]
Great. Thanks for the instructions.
Maibe somebody with some C++ skillz can make a utility app for that purpose.
Dziękuję.

**Comment by mihero** [comment]
Hi, I have first version done for eeprom stored callsign in sceensaver.
New settings screen for changing it.
https://github.com/mihero/rx5808-pro-diversity-pro58/tree/feature/callsign
Screensaver screen needs still bit tuning.
Any proposal for additional info into callsign screen?
I was thinking to add current diversity mode.
callsign is limited to 8 char.

**Comment by piodabro** [comment]
If you think its ready to publish, then make pull request ;)
Once i test it, we can make new version (FS buttons and callsign)

**Comment by mihero** [comment]
This has been a bit on hold.
I will finish it with just editable callsign.
Add other stuff then on another pr if needed.
pr #7 open

**Comment by piodabro** [comment]
Editable callsign done.
Big thanks to mihero!

Closing
